#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Use username as param"
    exit 1
fi

HOME_DIR=$(eval echo "~$1")

if [ -d "$HOME_DIR" ]; then
    find "$HOME_DIR" -maxdepth 1 -exec du -h -d 1 {} + | sort -rh
else
    echo "Dir not found"
    exit 1
fi
