#!/bin/bash

if [ $# -ne 4 ]; then
    echo "First param must be path to project"
    echo "Second param must be archive name"
    echo "Third param must be path to destination"
    echo "Fourth param must be mod (1/2)"
    exit 1
fi

PROJECT_DIR="$1"
ARCHIVE_NAME="$2"
DEST_DIR="$3"

mkdir -p "$DEST_DIR"
if [ $4 -e 1 ]; then
    tar -cvf "$DEST_DIR/$ARCHIVE_NAME.tar" -C "$PROJECT_DIR" .
elif [ $4 -e 2 ]; then
    tar -czvf "$DEST_DIR/$ARCHIVE_NAME.tar.gz" -C "$PROJECT_DIR" .
else
   echo "Wrong mod"
   exit 1
fi

echo "Completed"
