#!/bin/bash


function PRINT_ARRAY {
    local ARRAY=("1" "2" "3")

    for ELEMENT in "${ARRAY[@]}"; do
        echo "$ELEMENT"
    done
}
PRINT_ARRAY
alias PRINT="PRINT_ARRAY"
PRINT
#Ask why is visible
echo "$ELEMENT"
