#!/bin/bash

if [ $# -eq 0 ]; then
    echo "No params"
    exit 1
fi

while [ -n "$1" ]; do
    case "$1" in
	-l) echo "This is my flat";;
        --long) echo "This is my flat";;
        --sparta-flag) echo "This is \\\// Sparta";;
        *)echo "$1 is not an option";;
    esac 
    shift
done
