version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase

