version: '3.8'

services:
  web:
   # image: stepanlushch/firstrepo:latest
    build:
      context: .
      dockerfile: Dockerfile.wait
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432"

volumes:
  postgres_data:
    external: true
