# postgres-headless-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  namespace: postgres-namespace
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
  - port: 5432
