#!/bin/bash

if [ $# -ne 3 ]; then
    echo "First param must be path to archive"
    echo "Second param must be path to destination"
    echo "Third param must be mod (1/2)"
    exit 1
fi

ARCHIVE_DIR="$1"
EXTRACT_DIR="$2"

mkdir -p "$EXTRACT_DIR"
if [ $3 = 1 ]; then
    tar -xvf "$ARCHIVE_DIR/archive.tar" -C "$EXTRACT_DIR"
elif [$3 = 2]; then
    tar -xzvf "$ARCHIVE_DIR/archive.tar.gz" -C "$EXTRACT_DIR"
else
    echo "Wrong mod"
    exit 1
fi
echo "Extracted in $EXTRACT_DIR"

