#!/bin/bash

if [ $# -eq 0 ]; then
    echo "No params"
    exit 1
fi

if [ $1 -eq 1 ]; then
    echo "This is my flat"
elif [ $1 -eq 2 ]; then
    echo "This is \\\// Sparta!"
else
    echo "$RANDOM"
fi

