#!/bin/bash

SOURCE_DIR="/home/stepan/scripts/01-hello-world/archives"    
DEST_DIR="/home/stepan/scripts/01-hello-world/sync_archives" 
LOG_FILE="/home/stepan/scripts/01-hello-world/logfile.log"

mkdir -p "$DEST_DIR"

rsync -av --update --log-file="$LOG_FILE" "$SOURCE_DIR/" "$DEST_DIR/"

echo "Синхронизация завершена в $(date)" >> "$LOG_FILE"
